global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Master Node API metrics
  - job_name: 'gto-master-node'
    static_configs:
      - targets: ['master-node:8001']
    scrape_interval: 5s
    metrics_path: /metrics

  # Compute Nodes metrics (if they expose metrics)
  - job_name: 'gto-compute-nodes'
    static_configs:
      - targets: ['compute-node-1:8001', 'compute-node-2:8001']
    scrape_interval: 10s
    metrics_path: /metrics

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 10s

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 30s

  # System metrics (if using node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
